### ndarray
mxnet.ndarray是mxnet中用于描述张量的库

In [2]:
import OpenSSL.SSL
import mxnet as mx
import mxnet.ndarray as nd

生成一个全是1，3行4列的矩阵

In [3]:
a=nd.ones((3,4))
a


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

生成一个符合正态分布的矩阵，分布的均值为0，方差是1，1行2列

In [28]:
y=nd.random_normal(0,1,shape=(1,2))
y


[[ 0.85240513  0.79687119]]
<NDArray 1x2 @cpu(0)>

使用.shape()函数返回张量的形状，并用于指定另外一个张量的形状

In [4]:
y=nd.random_normal(0,1,shape=a.shape)
y


[[ 0.23107234  0.30030754 -0.32433936  1.04932904]
 [ 0.7368623  -0.0097888   0.46656415  1.72023427]
 [ 0.87809837 -1.07333779 -0.86925656 -0.26717702]]
<NDArray 3x4 @cpu(0)>

### 自动求导
自动求导可以直接返回函数的导数，这样就可以使用与梯度相关的函数用于进行优化，自动求导的模块是mxnet.autograd

In [7]:
import mxnet.autograd as ad

这里使用.attach_grad()函数给需要求导的参数添加一个导数标记，代表我们需要对a求导

In [8]:
a.attach_grad()

使用ad.record()函数记录计算过程

In [9]:
with ad.record():
    y=a*a
    z=y+a+2

使用返回值的.backward()函数进行自动求导

In [10]:
z.backward()

使用被求导变量的.grad()函数返回具体的导数值

In [12]:
a.grad


[[ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]]
<NDArray 3x4 @cpu(0)>